const food = [
  {
    title: "Зайрмаг",
    img: "img/icecream.png",
    discount: "30%",
    category: "Хямдралтай",
    price: "4760₮",
  },
  {
    title: "Панкейк",
    img: "img/pancake.png",
    discount: "20%",
    category: "Хямдралтай",
    price: "4800₮",
  },
  {
    title: "Өглөөний хоолг",
    img: "img/breakfast.png",
    discount: "20%",
    category: "Хямдралтай",
    price: "4800₮",
  },
  {
    title: "Банана сендвич",
    img: "img/pic.png",
    discount: "20%",
    category: "Хямдралтай",
    price: "4800₮",
  },
  {
    title: "Салмон загас",
    img: "img/salmon.png",
    price: "11,800₮",
    category: "Үндсэн хоол",
  },
  {
    title: "Бөөрөнхий мах",
    img: "img/meatball.png",
    price: "14,000₮",
    category: "Үндсэн хоол",
  },
  {
    title: "Самрын нухаш",
    img: "img/peanut.png",
    price: "9800₮",
    category: "Үндсэн хоол",
  },
  {
    title: "Чикен бургер",
    img: "img/burger.png",
    price: "4800₮",
    category: "Үндсэн хоол",
  },
  {
    title: "Детокс салад",
    img: "img/salad.png",
    price: "6800₮",
    category: "Салад ба зууш",
  },
  {
    title: "Кобб салад",
    img: "img/saladkobb.png",
    price: "6800₮",
    category: "Салад ба зууш",
  },
  {
    title: "Авакадо салад",
    img: "img/saladavacado.png",
    price: "6800₮",
    category: "Салад ба зууш",
  },
  {
    title: "Сендвич",
    img: "img/sendvich.png",
    price: "4800₮",
    category: "Салад ба зууш",
  },
  {
    title: "Донатс",
    img: "img/donuts.png",
    price: "5800₮",
    category: "Амттан",
  },
  {
    title: "Орео дессерт",
    img: "img/oreodessert.png",
    price: "7800₮",
    category: "Амттан",
  },
  {
    title: "Вафли",
    img: "img/vavli.png",
    price: "5800₮",
    category: "Амттан",
  },
  {
    title: "Макрон",
    img: "img/makron.png",
    price: "3800₮",
    category: "Амттан",
  },
];
